### GET request to example server
GET http://localhost:8080/knowledge?question="When was Robert Taylor out of office?"
###
GET http://localhost:8080/knowledge?question="What happened in the company while Emily Thompson was out of office?"

###
GET http://localhost:8080/knowledge?question="My name is Stefan"

###
GET http://localhost:8080/knowledge?question="What is my name?"

###
GET http://localhost:8080/knowledge/ooo?name="Emily Thompson"

###
GET http://localhost:8080/knowledge/ooo/summary?name="Emily Thompson"

###
GET https://hacktech.local.lt/knowledge/ooo/summary?name="James Wilson"


